apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollouts-demo
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/gnunn1/rollouts-example.git
      revision: HEAD
      directories:
      - path: overlays/**/app-config.yaml
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "rollouts-demo"
      source:
        repoURL: https://github.com/gnunn1/rollouts-example.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: '{{ destination }}'
        namespace: '{{.path.basename}}'
