apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollouts-demo
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/gnunn1/rollouts-example.git
      revision: HEAD
      files:
      - path: overlays/**/app-config.yaml
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: environment
              operator: In
              values:
                - dev

        - matchExpressions:
            - key: environment
              operator: In
              values:
                - staging

        - matchExpressions:
            - key: environment
              operator: In
              values:
                - prod

  template:
    metadata:
      labels:
        environment: '{{.path.basename}}'
      name: 'rollouts-demo-{{.path.basename}}'
    spec:
      project: "rollouts-demo"
      source:
        repoURL: https://github.com/gnunn1/rollouts-example.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: '{{ .destination }}'
        namespace: 'rollouts-demo-{{.path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
