apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-admin-binding.yaml
- cluster-monitoring-auth.yaml
- argocd.yaml
- rolloutmanager.yaml
- rollouts-demo-appproject.yaml
- image-updater.yaml
