apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-demo-stage

resources:
- namespace.yaml
- ../../base

patches:
  - patch: |
  - patch: |
      - op: replace
        path: /spec/strategy/canary/steps/1/args/0/value
        value: rollouts-demo-stage
      - op: replace
        path: /spec/strategy/canary/steps/1/args/2/value
        value: canary-canary-rollouts-demo-stage.apps.uthtest1.sandbox694.opentlc.com
    target:
      kind: Rollout
      name: rollouts-demo
