apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- monitor-auth.yaml
- canary-analysis.yaml
- rollout.yaml
- services.yaml
- route.yaml
images:
- name: quay.io/gnunn/rollouts-demo
  newTag: v1.0.5
